---
- hosts: 'centos2'
  become: true
  roles:
  - {role: build_app, tags: ['build_app']}
#  - {role: deploy_app, tags: ['deploy_app']}

- hosts: 'centos2'
  tasks:
    - name: debug test - hostvars
      debug: var=hostvars[inventory_hostname]
      tags: ["debug"]
