---
#  - name: st0p container tomcat
#    command: "docker stop tomcat"
#    ignore_errors: yes

#  - name: remove container tomcat
#    command: "docker rm tomcat"
#    ignore_errors: yes

  - name: Template docker-compose
    template:
      src: docker/docker-compose.yml.j2
      dest: {{ playbook_dir }}/docker-compose.yml