---
  - name: st0p container maven
    command: "docker stop maven"
    ignore_errors: yes

  - name: delete container maven
    command: "docker rm maven"
    ignore_errors: yes

  - name: build app
    block:
      - command: 'docker run -v {{ PATH_SOURCE_CODE }}:{{ PATH_SOURCE_CODE }} -w {{ PATH_SOURCE_CODE }} --name=maven -e DB_HOST -e DB_PORT -e DB_NAME -e DB_USERNAME -e DB_PASSWORD  maven:3.5.3-jdk-8-alpine mvn clean install'
        args:
          chdir: "{{ PATH_SOURCE_CODE }}"
        register: rMaven

      - file:
          path: "/patch/{{ SP_VERSION }}"
          state: directory
          mode: 0755

      - command:  "cp -R {{ PATH_SOURCE_CODE }}/target/* /patch/{{ SP_VERSION }}"
        args:
          chdir: "{{ PATH_SOURCE_CODE }}"
    rescue:
      - debug: msg="Error build maven!"
      - name: Putfile Error
        blockinfile:
          create: yes
          path: /opt/jenkins/error.log
          insertafter: EOF
          marker: ----------------------------------------------
          block: |
           Error build maven. Код возврата: {{ rMaven.rc }}
           stdout_lines: {{ rMaven.stdout_lines }}
           stderr_lines: {{ rMaven.stderr_lines }}
