---
  - name: st0p container maven
    command: "docker stop maven"
    ignore_errors: yes

  - name: delete container maven
    command: "docker rm maven"
    ignore_errors: yes

  - name: build app
    block:
      - command: 'docker run -v {{ PATH_SOURCE_CODE }}:{{ PATH_SOURCE_CODE }} -w {{ PATH_SOURCE_CODE }} --name=maven -e DB_HOST -e DB_PORT -e DB_NAME -e DB_USERNAME -e DB_PASSWORD  maven:3.5.3-jdk-8-alpine mvn clean install'
        args:
          chdir: "{{ PATH_SOURCE_CODE }}"
        register: rMaven
      - debug: msg="rMaven contains the word 'BUILD SUCCESS'"
        when: rMaven.stdout.find('BUILD SUCCESS') != -1
      - fail:
          msg: "Сборка не закончилась удачно: {{ rMaven.rc }} "
        when: rMaven.stdout.find('BUILD SUCCESS') == -1
      - file:
          path: "/patch/{{ SP_VERSION }}"
          state: directory
          mode: 0755
      - copy:
          src: "{{ PATH_SOURCE_CODE }}/target"
          dest: "/patch/{{ SP_VERSION }}"

